apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docs-app-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  rules:
  - host: docs.chorus-ai.co
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: docs-app
            port:
              number: 80